# Generated by Django 2.1.7 on 2019-04-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='myapp.User')),
                ('favorites', models.ManyToManyField(related_name='authorFavorites', to='myapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='description',
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='myapp.Author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='quoteFavorites', to='myapp.User'),
        ),
    ]
