# Generated by Django 2.1.7 on 2019-04-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190422_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='addedby',
        ),
        migrations.RemoveField(
            model_name='author',
            name='favorites',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='title',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.AlterField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='myapp.User'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
