# Generated by Django 2.1.7 on 2019-04-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190422_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
