# Generated by Django 2.1.7 on 2019-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='quoteFavorites', to='myapp.User'),
        ),
    ]
