# Generated by Django 2.1.7 on 2019-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190422_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='myapp.User'),
        ),
    ]
