# Generated by Django 2.1.7 on 2019-04-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190422_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='description',
        ),
    ]
